export { healthRoutes } from './health.js'
export { authRoutes, createAuthRoutes } from './auth.js'
export { campaignRoutes, createCampaignRoutes } from './campaigns.js'
export { bootstrapRoutes, createBootstrapRoutes } from './bootstrap.js'
export { squadRoutes, createSquadRoutes } from './squads.js'
export { missionRoutes, createMissionRoutes } from './missions.js'
export { reqRoutes, createReqRoutes } from './req.js'
